// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Eior4R5TkQr3mF5eNhuSqbs7MhCfEpk',
    appId: '1:509546631502:web:49a6b6246d4e61cdcc8e1f',
    messagingSenderId: '509546631502',
    projectId: 'instagram-clone-6092c',
    authDomain: 'instagram-clone-6092c.firebaseapp.com',
    storageBucket: 'instagram-clone-6092c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcH2nQoc2EOO2cMFWhala89f_VleINe9k',
    appId: '1:509546631502:android:d66a242344122c37cc8e1f',
    messagingSenderId: '509546631502',
    projectId: 'instagram-clone-6092c',
    storageBucket: 'instagram-clone-6092c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk_C_QKAwW9Dkx4oyIiLuijO0FbJ2mFNA',
    appId: '1:509546631502:ios:29c03a9ccc009510cc8e1f',
    messagingSenderId: '509546631502',
    projectId: 'instagram-clone-6092c',
    storageBucket: 'instagram-clone-6092c.appspot.com',
    iosClientId: '509546631502-po46rago594scnmbjm3ijpc25jt7cpvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk_C_QKAwW9Dkx4oyIiLuijO0FbJ2mFNA',
    appId: '1:509546631502:ios:29c03a9ccc009510cc8e1f',
    messagingSenderId: '509546631502',
    projectId: 'instagram-clone-6092c',
    storageBucket: 'instagram-clone-6092c.appspot.com',
    iosClientId: '509546631502-po46rago594scnmbjm3ijpc25jt7cpvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
